<?php	return array (
  'app' => 'Admin',
  'model' => 'Content',
  'action' => 'default',
  'data' => '',
  'type' => '0',
  'status' => '1',
  'name' => '内容管理',
  'icon' => 'th',
  'remark' => '',
  'listorder' => '10',
  'items' => 
  array (
    0 => 
    array (
      'app' => 'Admin',
      'model' => 'Term',
      'action' => 'index',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '分类管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    1 => 
    array (
      'app' => 'Admin',
      'model' => 'Page',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '页面管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
    ),
    2 => 
    array (
      'app' => 'Admin',
      'model' => 'Post',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '文章管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    3 => 
    array (
      'app' => 'Admin',
      'model' => 'Page',
      'action' => 'recyclebin',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '回收页面',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    4 => 
    array (
      'app' => 'Admin',
      'model' => 'Post',
      'action' => 'recyclebin',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '回收文章',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);?>